export const GET_ARTICLES = "GET_ARTICLES";
export const GET_SAVED_ARTICLES = "GET_SAVED_ARTICLES";
export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const REMOVE_SAVED_ARTICLE = "REMOVE_SAVED_ARTICLE";